### ISSUE TITLE
Progress Indicator is way to fast

### ISSUE THREAD

**Issue by 3lvis** [zenangst/WindowFlex#1]
Could you make it slower?

**Comment by zenangst** [comment]
I wonder if the progress indicator has a max width and it does not conform to the superviews total width.
I base this thesis on that if you make the window smaller it will go all the way.

Perhaps I can add an auto resizing mask to the subviews to make it work like one would expect.

**Comment by 3lvis** [comment]
Hopefully auto resizing mask works, sounds like the best solution, otherwise you will have to change the frame every time is needed.

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
